# Generated by Django 3.2.7 on 2021-09-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=80)),
                ('apelido', models.CharField(max_length=15)),
                ('cpf', models.CharField(db_index=True, max_length=15, unique=True)),
                ('rg', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nascimento', models.DateTimeField()),
                ('razao_social', models.CharField(max_length=80)),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=16)),
                ('tipo', models.CharField(choices=[('FIS', 'Física'), ('JUR', 'Jurídica')], default='FIS', max_length=3)),
                ('limite_fiado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('endereco', models.CharField(max_length=30)),
                ('endereco_numero', models.CharField(max_length=6)),
                ('endereco_complemento', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
