# Generated by Django 3.2.7 on 2021-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20211003_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
