# Generated by Django 3.2.7 on 2021-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20211005_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_complemento',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_fiado',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='apelido',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco_complemento',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
