# Generated by Django 3.2.7 on 2021-10-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20211003_2146'),
        ('produtos', '0002_auto_20210919_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fornecedores',
            field=models.ManyToManyField(null=True, related_name='categorias', to='pessoas.Fornecedor'),
        ),
        migrations.AddField(
            model_name='marca',
            name='fornecedores',
            field=models.ManyToManyField(null=True, related_name='marcas', to='pessoas.Fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedores',
            field=models.ManyToManyField(null=True, related_name='produtos', to='pessoas.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas', to='produtos.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.marca'),
        ),
    ]
